/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#74777e",
        "surface-container": "#e5eeff",
        "tertiary-fixed-dim": "#59dbc7",
        "primary": "#001229",
        "on-secondary-fixed": "#380d00",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#00201c",
        "primary-fixed": "#d4e3ff",
        "on-secondary-container": "#541700",
        "surface": "#f8f9ff",
        "on-tertiary-container": "#009f8e",
        "tertiary-fixed": "#79f7e3",
        "surface-bright": "#f8f9ff",
        "on-surface-variant": "#44474d",
        "on-secondary-fixed-variant": "#812900",
        "on-primary-fixed": "#021c39",
        "surface-container-highest": "#d3e4fe",
        "inverse-surface": "#213145",
        "outline-variant": "#c4c6ce",
        "surface-container-low": "#eff4ff",
        "surface-tint": "#4a5f7f",
        "primary-container": "#0f2744",
        "on-tertiary-fixed-variant": "#005047",
        "on-secondary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "secondary-fixed-dim": "#ffb59b",
        "tertiary-container": "#002c26",
        "on-primary-container": "#798fb1",
        "on-error-container": "#93000a",
        "secondary": "#a93800",
        "inverse-primary": "#b2c8ed",
        "primary-fixed-dim": "#b2c8ed",
        "on-primary-fixed-variant": "#324866",
        "secondary-container": "#ff5e15",
        "surface-dim": "#cbdbf5",
        "secondary-fixed": "#ffdbcf",
        "surface-variant": "#d3e4fe",
        "tertiary": "#001512",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "background": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "on-primary": "#ffffff"
      },
      spacing: {
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "margin": "3rem",
        "margin-mobile": "1.25rem",
        "gutter-mobile": "1rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        "title": ["Montserrat", "sans-serif"],
        "display": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "label-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-mobile": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "title": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "display": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "display-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "800" }]
      }
    }
  },
  plugins: [],
}
